# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 20:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_reactions', models.SmallIntegerField()),
                ('ppl_reactions', models.SmallIntegerField()),
                ('oth_reactions', models.SmallIntegerField()),
                ('notes', models.TextField()),
                ('date', models.DateField(default=datetime.date(2016, 12, 23))),
                ('modified', models.DateTimeField(default=datetime.datetime(2016, 12, 23, 20, 46, 30, 523439, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
