# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 20:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 23, 20, 51, 28, 78172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
