# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20161223_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='modified',
            new_name='Last_modified',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='notes',
            new_name='Notes',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='oth_reactions',
            new_name='Other_reactions',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='dog_reactions',
            new_name='Reactions_to_dogs',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='ppl_reactions',
            new_name='Reactions_to_people',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='created',
        ),
    ]
