# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20161223_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='Date',
            field=models.DateField(default=datetime.date(2017, 2, 11)),
        ),
    ]
